In [ ]:
% cd ..

In [ ]:
import Ipython

In [ ]:
!pip install Ipython

In [ ]:
!pip install numpy

In [ ]:
!pip install pandas

In [ ]:
!pip install metplotlib

In [ ]:
!pip install matplotlib

In [ ]:
%cd ..

In [1]:
%ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 44C3-662E

 C:\Users\USER\datavisual 디렉터리

2019-04-17  오후 02:35    <DIR>          .
2019-04-17  오후 02:35    <DIR>          ..
2019-04-17  오후 12:28    <DIR>          .ipynb_checkpoints
2019-04-17  오후 12:46                31 add.py
2019-04-17  오후 02:35            11,912 jupyter.ipynb
2019-04-17  오후 12:39                10 test.txt
2019-04-17  오후 12:40                10 test1.txt
               4개 파일              11,963 바이트
               3개 디렉터리  29,126,045,696 바이트 남음


In [ ]:
%cd datavisual/

In [ ]:
import numpy as np

In [ ]:
np.<tab>key 누르면 내부요소들 나옴
np.<shift+tab>key 누르면 내부요소들 나옴

In [ ]:
list?

In [ ]:
_+10

In [ ]:
1+1

In [ ]:
_+10

In [ ]:
%%writefile test.txt # 파일생성

In [ ]:
%%writefile test1.txt
인냥!!

In [ ]:
%ls

In [ ]:
%lsmagic

In [ ]:
%magic

In [ ]:
%debug

In [1]:
%run add.py

ERROR:root:File `'add.py'` not found.


In [2]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [4]:
%%capture

UsageError: %%capture is a cell magic, but the cell body is empty.


In [5]:
%whos

Interactive namespace is empty.


In [6]:
%quick

UsageError: Line magic function `%quick` not found.


In [7]:
%quickref

In [8]:
%%writefile add.py
def sum(a,b):
    return a+b

Writing add.py


In [9]:
%run add.py

In [10]:
sum(2,3)

5

numpy

# numpy

Numerical Python
C 언어로 구현된 저수준 고성능 라이브러리
반복문을 작성할 필요 없이 전체 데이터 배열에 대한 빠른 연산 지원
배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 올려진 파일에 사용하는 도구
빠르고 메모리를 효율적으로 사용하여 다차원 배열 ndarray지원
선형대수, 난수발생기, 푸리에 변환 기능

In [13]:
import numpy as np

In [17]:
ar_list = [i for i in range(20)]
np_list = np.array(ar_list)

In [23]:
print(ar_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [24]:
print(np_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
np_list.shape

(20,)

스칼라/벡터/행렬
스칼라는 number, 벡터는 숫자들의 list, 행렬은 숫자들의 array(rows, cols)

numpy 배열 (1/2)
numpy 배열을 만들 때는 np.array() 메소드 이용, np.array()는 파이썬의 리스트를 numpy,ndarray 형태로 변환, numpy는 다차원 행렬로 표현하고, 계산하기 쉬움

In [26]:
arr = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(arr)

In [27]:
print(arr) # 2차원의 리스트

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [28]:
print(arr2) # 행렬

[[1 2 3 4]
 [5 6 7 8]]


In [30]:
%timeit np_list*100 # 실행했을때 시간이 얼마나 걸렸냐. numpy가 시간이 훨씬 짧음

612 ns ± 2.58 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [31]:
%timeit ar_list*100

3.12 µs ± 17.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [32]:
arr2.ndim

2

In [33]:
arr2.shape

(2, 4)

In [34]:
arr2 * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
numpy배열
zeros: 0으로 초기화된 배열, ones: 1로 초기화된 배열
linespace: 선형구간에서 지정구간의 수만큼 분할
logspace: 로그구간에서 지정구간 만큼 분할
empty: 배열을 메모리에 생성만하고 특정한 값을 초기화 하지않는 배열(초기화 시간단축)

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [55]:
np.ones((2,3), int, 'C')

array([[1, 1, 1],
       [1, 1, 1]])