In [ ]:

b=0
for i in range(10,99):
    if i % 2==0 and (i/10)>4 and (i%10)>(i/10):
        b+=1
        print(i)
print(b)

In [ ]:
all=1000
b=all-200


i=987
i=str(i)
b=",".join(i)
print(b)


In [ ]:
while True:
    x=int(input("첫번째 숫자입력"))
    y=int(input("두번째 숫자 입력"))
    x1=x/10
    x10=x%10
    y1=y/10
    y10=y%10
    
    a=((x1+y1)*10)+x10+y10
    print(a)

In [9]:
for i in range(100,1000):
    c=str(i)
    d=""
    z=0
    if c[0]!=c[1] and c[1]!=c[2] and c[2]!=c[0]:
        i=int(c)
        if  c[1]== '8' and int(c[2])+int(c[1])==int(c[0]):
            print(i)
    
    

981


In [1]:
import numpy as np

In [2]:
c=int(input("행렬입력"))

g=np.zeros((c,c))
d=0
for i in range(1,c+1):
    for b in range(1,i*2):
        d+=1
        if i<b:
            g[(i*2-1)-b,i-1]=d
        elif i>b:
             g[i-1,b-1]=d
        else:
            g[i-1,i-1]=d

print(g)

행렬입력6
[[ 1.  4.  9. 16. 25. 36.]
 [ 2.  3.  8. 15. 24. 35.]
 [ 5.  6.  7. 14. 23. 34.]
 [10. 11. 12. 13. 22. 33.]
 [17. 18. 19. 20. 21. 32.]
 [26. 27. 28. 29. 30. 31.]]
